vim.o.guifont = 'IosevkaTerm Nerd Font:h12,IosevkaTerm Nerd Font Semibold:h12'
--vim.g.neovide_transparency = 1
vim.g.neovide_hide_mouse_when_typing = true
--vim.g.neovide_scale_factor = 0.75
vim.g.neovide_cursor_antialiasing = false
vim.g.neovide_remember_window_size = true
vim.g.neovide_padding_top = 4
vim.g.neovide_padding_bottom = 4
vim.g.neovide_padding_right = 4
vim.g.neovide_padding_left = 4
